
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'de' | 'ar' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.formino': 'Formino',
    'nav.termino': 'Termino',
    'nav.about': 'About Us',
    'nav.pricing': 'Pricing',
    'nav.help': 'Help',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.register': 'Register',
    
    // Hero
    'hero.subtitle': 'Your AI-Powered Administrative Assistant',
    'hero.title1': 'Eliminate Bureaucratic',
    'hero.title2': 'Complexities Forever',
    'hero.description': 'Mein Genie is your intelligent companion that transforms complex administrative tasks into simple conversations. Perfect for immigrants and seniors who want to navigate bureaucracy with confidence and ease.',
    'hero.startJourney': 'Start Your Journey',
    'hero.learnMore': 'Learn More',
    'hero.trusted': 'Trusted by thousands of users worldwide',
    'hero.callUs': 'Call us:',
    
    // Modules
    'modules.title': 'Two Powerful Modules, One Solution',
    'modules.subtitle': 'Choose the module that fits your needs, or use both to completely streamline your administrative tasks.',
    'modules.formino.title': 'Formino',
    'modules.formino.subtitle': 'Intelligent Form Assistant',
    'modules.formino.description': 'Transform complex paper forms into simple voice conversations. Upload, scan, or link any form, then chat with our AI in your native language to fill it out perfectly.',
    'modules.formino.feature1': 'Voice conversation in your language',
    'modules.formino.feature2': 'OCR for paper form scanning',
    'modules.formino.feature3': 'Human review before submission',
    'modules.formino.button': 'Explore Formino',
    'modules.termino.title': 'Termino',
    'modules.termino.subtitle': 'Smart Appointment Booking',
    'modules.termino.description': 'Never wait on hold again. Our AI makes phone calls for you, books appointments, and manages your calendar automatically. Perfect for doctor visits, government offices, and more.',
    'modules.termino.feature1': 'AI-powered phone calls',
    'modules.termino.feature2': 'Automatic calendar synchronization',
    'modules.termino.feature3': '24/7 appointment monitoring',
    'modules.termino.button': 'Explore Termino',
    
    // Features
    'features.title': 'Everything You Need in One Platform',
    'features.subtitle': 'Mein Genie combines cutting-edge AI technology with human empathy to create the most comprehensive administrative assistance platform available.',
    'features.ai.title': 'Voice conversation in 15+ languages',
    'features.ai.description': 'Advanced natural language processing that understands context and nuance in multiple languages.',
    'features.security.title': 'OCR scanning for paper documents',
    'features.security.description': 'Bank-level encryption and security protocols to protect your sensitive information.',
    'features.support.title': 'Automatic appointment booking',
    'features.support.description': 'Real people available around the clock to help when you need assistance.',
    'features.integration.title': 'Human advisor support',
    'features.integration.description': 'Works with existing systems and platforms you already use.',
    'features.multilingual.title': 'Secure document storage',
    'features.multilingual.description': 'Full support for multiple languages with native-level understanding.',
    'features.accessibility.title': 'Calendar integration',
    'features.accessibility.description': 'Designed for users of all abilities with comprehensive accessibility features.',
    'features.realtime.title': 'Real-time form processing',
    'features.realtime.description': 'Process forms instantly with real-time AI assistance and validation.',
    'features.availability.title': '24/7 availability',
    'features.availability.description': 'Our platform is available around the clock to assist you whenever needed.',
    'features.learnMore': 'Learn More',
    
    // Why Mein Genie
    'why.title': 'Why Choose Mein Genie?',
    'why.subtitle': 'Join thousands who have already simplified their administrative lives.',
    'why.timeSaved.title': 'Time Saved',
    'why.timeSaved.description': 'Average 5 hours saved per week on administrative tasks.',
    'why.accuracy.title': 'Accuracy Rate',
    'why.accuracy.description': 'AI-powered form completion with human verification.',
    'why.satisfaction.title': 'User Satisfaction',
    'why.satisfaction.description': 'Rated excellent by users across all demographics.',
    'why.languages.title': 'Languages Supported',
    'why.languages.description': 'Full support for major world languages.',
    
    // Testimonials
    'testimonials.title': 'What Our Users Say',
    'testimonials.subtitle': 'Real stories from people who have transformed their administrative experience.',
    
    // Footer
    'footer.description': 'Transforming bureaucracy through intelligent automation and human empathy.',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.rights': 'All rights reserved.',
    
    // Pages
    'formino.title': 'Formino - Intelligent Form Assistant',
    'formino.subtitle': 'Transform any form into a simple conversation',
    'formino.description': 'Upload, scan, or link any government form, application, or document. Our AI will guide you through filling it out in your native language.',
    'formino.howItWorks': 'How It Works',
    'formino.step1': 'Upload or scan your form',
    'formino.step2': 'Chat with our AI in your language',
    'formino.step3': 'Review and submit your completed form',
    'formino.getStarted': 'Get Started',
    
    'termino.title': 'Termino - Smart Appointment Booking',
    'termino.subtitle': 'Never wait on hold again',
    'termino.description': 'Our AI assistant makes phone calls for you, books appointments, and manages your calendar automatically.',
    'termino.howItWorks': 'How It Works',
    'termino.step1': 'Tell us what appointment you need',
    'termino.step2': 'Our AI calls and books for you',
    'termino.step3': 'Receive confirmation and calendar update',
    'termino.getStarted': 'Get Started',
    
    'about.title': 'About Mein Genie',
    'about.subtitle': 'Simplifying bureaucracy for everyone',
    'about.description': 'We believe that navigating government services and administrative tasks should be simple, accessible, and stress-free for everyone, regardless of language barriers or technical expertise.',
    'about.mission': 'Our Mission',
    'about.missionText': 'To eliminate bureaucratic barriers and empower individuals to access services and complete administrative tasks with confidence and ease.',
    'about.vision': 'Our Vision',
    'about.visionText': 'A world where language barriers and complex forms never prevent anyone from accessing the services they need.',
    
    'pricing.title': 'Choose Your Plan',
    'pricing.subtitle': 'Flexible pricing for individuals and families',
    'pricing.basic': 'Basic',
    'pricing.pro': 'Pro',
    'pricing.enterprise': 'Enterprise',
    'pricing.monthly': 'per month',
    'pricing.yearly': 'per year',
    'pricing.features': 'Features included:',
    'pricing.getStarted': 'Get Started',
    'pricing.contactUs': 'Contact Us',
    
    'help.title': 'Help Center',
    'help.subtitle': 'Find answers to your questions',
    'help.faq': 'Frequently Asked Questions',
    'help.guides': 'User Guides',
    'help.contact': 'Contact Support',
    'help.searchPlaceholder': 'Search for help...',
    
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.hours': 'Business Hours',
    
    // Common
    'common.download': 'Download PDF File',
    'common.upload': 'Upload File',
    'common.camera': 'Scan with Camera',
    'common.microphone': 'Voice Interaction',
    'common.chat': 'Text Chat',
    'common.review': 'Review Form',
    'common.support': 'Get Support',
    'common.loading': 'Loading...',
    'common.error': 'Error occurred',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.formino': 'Formino',
    'nav.termino': 'Termino',
    'nav.about': 'Über uns',
    'nav.pricing': 'Preise',
    'nav.help': 'Hilfe',
    'nav.contact': 'Kontakt',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    
    // Hero
    'hero.subtitle': 'Ihr KI-gestützter Verwaltungsassistent',
    'hero.title1': 'Bürokratische Komplexitäten',
    'hero.title2': 'für immer beseitigen',
    'hero.description': 'Mein Genie ist Ihr intelligenter Begleiter, der komplexe Verwaltungsaufgaben in einfache Gespräche verwandelt. Perfekt für Einwanderer und Senioren, die die Bürokratie mit Vertrauen und Leichtigkeit navigieren möchten.',
    'hero.startJourney': 'Reise beginnen',
    'hero.learnMore': 'Mehr erfahren',
    'hero.trusted': 'Vertraut von Tausenden von Nutzern weltweit',
    'hero.callUs': 'Rufen Sie uns an:',
    
    // Modules
    'modules.title': 'Zwei starke Module, eine Lösung',
    'modules.subtitle': 'Wählen Sie das Modul, das Ihren Bedürfnissen entspricht, oder verwenden Sie beide, um Ihre Verwaltungsaufgaben vollständig zu rationalisieren.',
    'modules.formino.title': 'Formino',
    'modules.formino.subtitle': 'Intelligenter Formular-Assistent',
    'modules.formino.description': 'Verwandeln Sie komplexe Papierformulare in einfache Sprachgespräche. Laden Sie Formulare hoch, scannen Sie sie oder verlinken Sie sie, und chatten Sie dann mit unserer KI in Ihrer Muttersprache, um sie perfekt auszufüllen.',
    'modules.formino.feature1': 'Sprachunterhaltung in Ihrer Sprache',
    'modules.formino.feature2': 'OCR zum Scannen von Papierformularen',
    'modules.formino.feature3': 'Menschliche Überprüfung vor der Einreichung',
    'modules.formino.button': 'Formino erkunden',
    'modules.termino.title': 'Termino',
    'modules.termino.subtitle': 'Intelligente Terminbuchung',
    'modules.termino.description': 'Nie wieder in der Warteschleife warten. Unsere KI führt Telefonate für Sie, bucht Termine und verwaltet Ihren Kalender automatisch. Perfekt für Arztbesuche, Behördengänge und mehr.',
    'modules.termino.feature1': 'KI-gestützte Telefonate',
    'modules.termino.feature2': 'Automatische Kalender-Synchronisation',
    'modules.termino.feature3': '24/7 Terminüberwachung',
    'modules.termino.button': 'Termino erkunden',
    
    // Features
    'features.title': 'Alles was Sie brauchen in einer Plattform',
    'features.subtitle': 'Mein Genie kombiniert modernste KI-Technologie mit menschlicher Empathie, um die umfassendste administrative Assistenzplattform zu schaffen.',
    'features.ai.title': 'Sprachunterhaltung in 15+ Sprachen',
    'features.ai.description': 'Fortgeschrittene Sprachverarbeitung, die Kontext und Nuancen in mehreren Sprachen versteht.',
    'features.security.title': 'OCR-Scannen für Papierdokumente',
    'features.security.description': 'Bankniveau-Verschlüsselung und Sicherheitsprotokolle zum Schutz Ihrer sensiblen Informationen.',
    'features.support.title': 'Automatische Terminbuchung',
    'features.support.description': 'Echte Menschen rund um die Uhr verfügbar, um zu helfen, wenn Sie Unterstützung benötigen.',
    'features.integration.title': 'Menschliche Beraterunterstützung',
    'features.integration.description': 'Funktioniert mit bestehenden Systemen und Plattformen, die Sie bereits verwenden.',
    'features.multilingual.title': 'Sichere Dokumentenspeicherung',
    'features.multilingual.description': 'Vollständige Unterstützung für mehrere Sprachen mit muttersprachlichem Verständnis.',
    'features.accessibility.title': 'Kalender-Integration',
    'features.accessibility.description': 'Entwickelt für Benutzer aller Fähigkeiten mit umfassenden Barrierefreiheitsfunktionen.',
    'features.realtime.title': 'Echtzeit-Formularverarbeitung',
    'features.realtime.description': 'Verarbeiten Sie Formulare sofort mit Echtzeit-KI-Unterstützung und Validierung.',
    'features.availability.title': '24/7 Verfügbarkeit',
    'features.availability.description': 'Unsere Plattform ist rund um die Uhr verfügbar, um Ihnen zu helfen, wann immer Sie es brauchen.',
    'features.learnMore': 'Mehr erfahren',
    
    // Why Mein Genie
    'why.title': 'Warum Mein Genie wählen?',
    'why.subtitle': 'Schließen Sie sich Tausenden an, die bereits ihr Verwaltungsleben vereinfacht haben.',
    'why.timeSaved.title': 'Gesparte Zeit',
    'why.timeSaved.description': 'Durchschnittlich 5 Stunden pro Woche bei Verwaltungsaufgaben gespart.',
    'why.accuracy.title': 'Genauigkeitsrate',
    'why.accuracy.description': 'KI-gestützte Formularausfüllung mit menschlicher Überprüfung.',
    'why.satisfaction.title': 'Benutzerzufriedenheit',
    'why.satisfaction.description': 'Von Benutzern aller Demografien als ausgezeichnet bewertet.',
    'why.languages.title': 'Unterstützte Sprachen',
    'why.languages.description': 'Vollständige Unterstützung für wichtige Weltsprachen.',
    
    // Testimonials
    'testimonials.title': 'Was unsere Benutzer sagen',
    'testimonials.subtitle': 'Echte Geschichten von Menschen, die ihre Verwaltungserfahrung transformiert haben.',
    
    // Footer
    'footer.description': 'Transformation der Bürokratie durch intelligente Automatisierung und menschliche Empathie.',
    'footer.product': 'Produkt',
    'footer.company': 'Unternehmen',
    'footer.support': 'Support',
    'footer.legal': 'Rechtliches',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.cookies': 'Cookie-Richtlinie',
    'footer.rights': 'Alle Rechte vorbehalten.',
    
    // Pages
    'formino.title': 'Formino - Intelligenter Formular-Assistent',
    'formino.subtitle': 'Verwandeln Sie jedes Formular in ein einfaches Gespräch',
    'formino.description': 'Laden Sie staatliche Formulare, Anträge oder Dokumente hoch, scannen oder verlinken Sie sie. Unsere KI führt Sie durch das Ausfüllen in Ihrer Muttersprache.',
    'formino.howItWorks': 'Wie es funktioniert',
    'formino.step1': 'Laden Sie Ihr Formular hoch oder scannen Sie es',
    'formino.step2': 'Chatten Sie mit unserer KI in Ihrer Sprache',
    'formino.step3': 'Überprüfen und senden Sie Ihr ausgefülltes Formular',
    'formino.getStarted': 'Loslegen',
    
    'termino.title': 'Termino - Intelligente Terminbuchung',
    'termino.subtitle': 'Nie wieder in der Warteschleife warten',
    'termino.description': 'Unser KI-Assistent führt Telefonate für Sie, bucht Termine und verwaltet Ihren Kalender automatisch.',
    'termino.howItWorks': 'Wie es funktioniert',
    'termino.step1': 'Sagen Sie uns, welchen Termin Sie benötigen',
    'termino.step2': 'Unsere KI ruft an und bucht für Sie',
    'termino.step3': 'Erhalten Sie Bestätigung und Kalender-Update',
    'termino.getStarted': 'Loslegen',
    
    'about.title': 'Über Mein Genie',
    'about.subtitle': 'Bürokratie für alle vereinfachen',
    'about.description': 'Wir glauben, dass die Navigation von Regierungsdiensten und Verwaltungsaufgaben einfach, zugänglich und stressfrei für alle sein sollte, unabhängig von Sprachbarrieren oder technischem Fachwissen.',
    'about.mission': 'Unsere Mission',
    'about.missionText': 'Bürokratische Barrieren zu beseitigen und Einzelpersonen zu befähigen, Dienstleistungen zu nutzen und Verwaltungsaufgaben mit Vertrauen und Leichtigkeit zu erledigen.',
    'about.vision': 'Unsere Vision',
    'about.visionText': 'Eine Welt, in der Sprachbarrieren und komplexe Formulare niemals jemanden daran hindern, die benötigten Dienstleistungen zu erhalten.',
    
    'pricing.title': 'Wählen Sie Ihren Plan',
    'pricing.subtitle': 'Flexible Preise für Einzelpersonen und Familien',
    'pricing.basic': 'Basic',
    'pricing.pro': 'Pro',
    'pricing.enterprise': 'Enterprise',
    'pricing.monthly': 'pro Monat',
    'pricing.yearly': 'pro Jahr',
    'pricing.features': 'Enthaltene Funktionen:',
    'pricing.getStarted': 'Loslegen',
    'pricing.contactUs': 'Kontaktieren Sie uns',
    
    'help.title': 'Hilfe-Center',
    'help.subtitle': 'Finden Sie Antworten auf Ihre Fragen',
    'help.faq': 'Häufig gestellte Fragen',
    'help.guides': 'Benutzerhandbücher',
    'help.contact': 'Support kontaktieren',
    'help.searchPlaceholder': 'Nach Hilfe suchen...',
    
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Nehmen Sie Kontakt mit unserem Team auf',
    'contact.name': 'Vollständiger Name',
    'contact.email': 'E-Mail-Adresse',
    'contact.subject': 'Betreff',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht senden',
    'contact.phone': 'Telefon',
    'contact.address': 'Adresse',
    'contact.hours': 'Geschäftszeiten',
    
    // Common
    'common.download': 'PDF-Datei herunterladen',
    'common.upload': 'Datei hochladen',
    'common.camera': 'Mit Kamera scannen',
    'common.microphone': 'Sprachinteraktion',
    'common.chat': 'Text-Chat',
    'common.review': 'Formular überprüfen',
    'common.support': 'Unterstützung erhalten',
    'common.loading': 'Wird geladen...',
    'common.error': 'Fehler aufgetreten',
    'common.success': 'Erfolgreich',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.formino': 'فورمينو',
    'nav.termino': 'تيرمينو',
    'nav.about': 'معلومات عنا',
    'nav.pricing': 'الأسعار',
    'nav.help': 'المساعدة',
    'nav.contact': 'اتصل بنا',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'التسجيل',
    
    // Hero
    'hero.subtitle': 'مساعدك الإداري المدعوم بالذكاء الاصطناعي',
    'hero.title1': 'القضاء على التعقيدات',
    'hero.title2': 'البيروقراطية إلى الأبد',
    'hero.description': 'مين جيني هو رفيقك الذكي الذي يحول المهام الإدارية المعقدة إلى محادثات بسيطة. مثالي للمهاجرين وكبار السن الذين يريدون التنقل في البيروقراطية بثقة وسهولة.',
    'hero.startJourney': 'ابدأ رحلتك',
    'hero.learnMore': 'اعرف المزيد',
    'hero.trusted': 'يثق به آلاف المستخدمين حول العالم',
    'hero.callUs': 'اتصل بنا:',
    
    // Modules
    'modules.title': 'وحدتان قويتان، حل واحد',
    'modules.subtitle': 'اختر الوحدة التي تناسب احتياجاتك، أو استخدم كلاهما لتبسيط مهامك الإدارية بالكامل.',
    'modules.formino.title': 'فورمينو',
    'modules.formino.subtitle': 'مساعد النماذج الذكي',
    'modules.formino.description': 'حول النماذج الورقية المعقدة إلى محادثات صوتية بسيطة. ارفع النماذج أو امسحها ضوئياً أو اربطها، ثم تحدث مع الذكاء الاصطناعي بلغتك الأم لملئها بشكل مثالي.',
    'modules.formino.feature1': 'محادثة صوتية بلغتك',
    'modules.formino.feature2': 'OCR لمسح النماذج الورقية',
    'modules.formino.feature3': 'مراجعة بشرية قبل الإرسال',
    'modules.formino.button': 'استكشف فورمينو',
    'modules.termino.title': 'تيرمينو',
    'modules.termino.subtitle': 'حجز المواعيد الذكي',
    'modules.termino.description': 'لا تنتظر في قائمة الانتظار مرة أخرى. يقوم الذكاء الاصطناعي بإجراء المكالمات الهاتفية نيابة عنك، ويحجز المواعيد، ويدير تقويمك تلقائياً. مثالي لزيارات الطبيب والمكاتب الحكومية والمزيد.',
    'modules.termino.feature1': 'مكالمات هاتفية مدعومة بالذكاء الاصطناعي',
    'modules.termino.feature2': 'مزامنة التقويم التلقائية',
    'modules.termino.feature3': 'مراقبة المواعيد على مدار الساعة',
    'modules.termino.button': 'استكشف تيرمينو',
    
    // Features
    'features.title': 'كل ما تحتاجه في منصة واحدة',
    'features.subtitle': 'يجمع مين جيني بين أحدث تقنيات الذكاء الاصطناعي والتعاطف البشري لإنشاء أشمل منصة مساعدة إدارية متاحة.',
    'features.ai.title': 'محادثة صوتية بأكثر من 15 لغة',
    'features.ai.description': 'معالجة متقدمة للغة الطبيعية تفهم السياق والفروق الدقيقة في لغات متعددة.',
    'features.security.title': 'مسح OCR للمستندات الورقية',
    'features.security.description': 'تشفير على مستوى البنوك وبروتوكولات أمان لحماية معلوماتك الحساسة.',
    'features.support.title': 'حجز المواعيد التلقائي',
    'features.support.description': 'أشخاص حقيقيون متاحون على مدار الساعة للمساعدة عندما تحتاج إلى المساعدة.',
    'features.integration.title': 'دعم المستشار البشري',
    'features.integration.description': 'يعمل مع الأنظمة والمنصات الموجودة التي تستخدمها بالفعل.',
    'features.multilingual.title': 'تخزين آمن للمستندات',
    'features.multilingual.description': 'دعم كامل للغات متعددة بفهم على مستوى اللغة الأم.',
    'features.accessibility.title': 'تكامل التقويم',
    'features.accessibility.description': 'مصمم للمستخدمين من جميع القدرات مع ميزات إمكانية وصول شاملة.',
    'features.realtime.title': 'معالجة النماذج في الوقت الفعلي',
    'features.realtime.description': 'معالجة النماذج فوراً مع مساعدة وتحقق الذكاء الاصطناعي في الوقت الفعلي.',
    'features.availability.title': 'متاح على مدار الساعة',
    'features.availability.description': 'منصتنا متاحة على مدار الساعة لمساعدتك كلما احتجت.',
    'features.learnMore': 'اعرف المزيد',
    
    // Why Mein Genie
    'why.title': 'لماذا تختار مين جيني؟',
    'why.subtitle': 'انضم إلى الآلاف الذين بسطوا بالفعل حياتهم الإدارية.',
    'why.timeSaved.title': 'الوقت المُوفر',
    'why.timeSaved.description': 'متوسط 5 ساعات موفرة أسبوعياً في المهام الإدارية.',
    'why.accuracy.title': 'معدل الدقة',
    'why.accuracy.description': 'إكمال النماذج بالذكاء الاصطناعي مع التحقق البشري.',
    'why.satisfaction.title': 'رضا المستخدم',
    'why.satisfaction.description': 'مُصنف كممتاز من قبل المستخدمين عبر جميع الفئات الديموغرافية.',
    'why.languages.title': 'اللغات المدعومة',
    'why.languages.description': 'دعم كامل للغات العالمية الرئيسية.',
    
    // Testimonials
    'testimonials.title': 'ما يقوله مستخدمونا',
    'testimonials.subtitle': 'قصص حقيقية من أشخاص حولوا تجربتهم الإدارية.',
    
    // Footer
    'footer.description': 'تحويل البيروقراطية من خلال الأتمتة الذكية والتعاطف البشري.',
    'footer.product': 'المنتج',
    'footer.company': 'الشركة',
    'footer.support': 'الدعم',
    'footer.legal': 'قانوني',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.cookies': 'سياسة ملفات تعريف الارتباط',
    'footer.rights': 'جميع الحقوق محفوظة.',
    
    // Pages
    'formino.title': 'فورمينو - مساعد النماذج الذكي',
    'formino.subtitle': 'حول أي نموذج إلى محادثة بسيطة',
    'formino.description': 'ارفع أو امسح أو اربط أي نموذج حكومي أو طلب أو وثيقة. سيقوم الذكاء الاصطناعي بإرشادك خلال ملئه بلغتك الأم.',
    'formino.howItWorks': 'كيف يعمل',
    'formino.step1': 'ارفع أو امسح نموذجك',
    'formino.step2': 'تحدث مع الذكاء الاصطناعي بلغتك',
    'formino.step3': 'راجع وأرسل نموذجك المكتمل',
    'formino.getStarted': 'ابدأ',
    
    'termino.title': 'تيرمينو - حجز المواعيد الذكي',
    'termino.subtitle': 'لا تنتظر في قائمة الانتظار مرة أخرى',
    'termino.description': 'مساعد الذكاء الاصطناعي يقوم بالمكالمات الهاتفية نيابة عنك، ويحجز المواعيد، ويدير تقويمك تلقائياً.',
    'termino.howItWorks': 'كيف يعمل',
    'termino.step1': 'أخبرنا عن الموعد الذي تحتاجه',
    'termino.step2': 'الذكاء الاصطناعي يتصل ويحجز لك',
    'termino.step3': 'تلقي التأكيد وتحديث التقويم',
    'termino.getStarted': 'ابدأ',
    
    'about.title': 'حول مين جيني',
    'about.subtitle': 'تبسيط البيروقراطية للجميع',
    'about.description': 'نحن نؤمن أن التنقل في الخدمات الحكومية والمهام الإدارية يجب أن يكون بسيطاً ومتاحاً وخالياً من الإجهاد للجميع، بغض النظر عن حواجز اللغة أو الخبرة التقنية.',
    'about.mission': 'مهمتنا',
    'about.missionText': 'القضاء على الحواجز البيروقراطية وتمكين الأفراد من الوصول إلى الخدمات وإكمال المهام الإدارية بثقة وسهولة.',
    'about.vision': 'رؤيتنا',
    'about.visionText': 'عالم لا تمنع فيه الحواجز اللغوية والنماذج المعقدة أي شخص من الوصول إلى الخدمات التي يحتاجها.',
    
    'pricing.title': 'اختر خطتك',
    'pricing.subtitle': 'أسعار مرنة للأفراد والعائلات',
    'pricing.basic': 'أساسي',
    'pricing.pro': 'احترافي',
    'pricing.enterprise': 'مؤسسي',
    'pricing.monthly': 'شهرياً',
    'pricing.yearly': 'سنوياً',
    'pricing.features': 'الميزات المشمولة:',
    'pricing.getStarted': 'ابدأ',
    'pricing.contactUs': 'اتصل بنا',
    
    'help.title': 'مركز المساعدة',
    'help.subtitle': 'اعثر على إجابات لأسئلتك',
    'help.faq': 'الأسئلة الشائعة',
    'help.guides': 'أدلة المستخدم',
    'help.contact': 'اتصل بالدعم',
    'help.searchPlaceholder': 'البحث عن المساعدة...',
    
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'تواصل مع فريقنا',
    'contact.name': 'الاسم الكامل',
    'contact.email': 'عنوان البريد الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'contact.phone': 'الهاتف',
    'contact.address': 'العنوان',
    'contact.hours': 'ساعات العمل',
    
    // Common
    'common.download': 'تحميل ملف PDF',
    'common.upload': 'رفع ملف',
    'common.camera': 'مسح بالكاميرا',
    'common.microphone': 'التفاعل الصوتي',
    'common.chat': 'دردشة نصية',
    'common.review': 'مراجعة النموذج',
    'common.support': 'الحصول على الدعم',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'نجح',
    'common.back': 'العودة',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.formino': 'Formino',
    'nav.termino': 'Termino',
    'nav.about': 'Acerca de',
    'nav.pricing': 'Precios',
    'nav.help': 'Ayuda',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar sesión',
    'nav.register': 'Registrarse',
    
    // Hero
    'hero.subtitle': 'Tu Asistente Administrativo Impulsado por IA',
    'hero.title1': 'Elimina las Complejidades',
    'hero.title2': 'Burocráticas para Siempre',
    'hero.description': 'Mein Genie es tu compañero inteligente que transforma tareas administrativas complejas en conversaciones simples. Perfecto para inmigrantes y personas mayores que quieren navegar la burocracia con confianza y facilidad.',
    'hero.startJourney': 'Comienza tu Viaje',
    'hero.learnMore': 'Saber Más',
    'hero.trusted': 'Confiado por miles de usuarios en todo el mundo',
    'hero.callUs': 'Llámanos:',
    
    // Modules
    'modules.title': 'Dos Módulos Poderosos, Una Solución',
    'modules.subtitle': 'Elige el módulo que se adapte a tus necesidades, o usa ambos para simplificar completamente tus tareas administrativas.',
    'modules.formino.title': 'Formino',
    'modules.formino.subtitle': 'Asistente Inteligente de Formularios',
    'modules.formino.description': 'Transforma formularios de papel complejos en conversaciones de voz simples. Sube, escanea o enlaza cualquier formulario, luego chatea con nuestra IA en tu idioma nativo para completarlo perfectamente.',
    'modules.formino.feature1': 'Conversación por voz en tu idioma',
    'modules.formino.feature2': 'OCR para escaneo de formularios en papel',
    'modules.formino.feature3': 'Revisión humana antes del envío',
    'modules.formino.button': 'Explorar Formino',
    'modules.termino.title': 'Termino',
    'modules.termino.subtitle': 'Reserva Inteligente de Citas',
    'modules.termino.description': 'Nunca más esperes en espera. Nuestra IA hace llamadas telefónicas por ti, reserva citas y gestiona tu calendario automáticamente. Perfecto para visitas médicas, oficinas gubernamentales y más.',
    'modules.termino.feature1': 'Llamadas telefónicas impulsadas por IA',
    'modules.termino.feature2': 'Sincronización automática del calendario',
    'modules.termino.feature3': 'Monitoreo de citas 24/7',
    'modules.termino.button': 'Explorar Termino',
    
    // Features
    'features.title': 'Todo lo que Necesitas en Una Plataforma',
    'features.subtitle': 'Mein Genie combina tecnología de IA de vanguardia con empatía humana para crear la plataforma de asistencia administrativa más completa disponible.',
    'features.ai.title': 'Conversación por voz en más de 15 idiomas',
    'features.ai.description': 'Procesamiento avanzado de lenguaje natural que entiende contexto y matices en múltiples idiomas.',
    'features.security.title': 'Escaneo OCR para documentos en papel',
    'features.security.description': 'Cifrado de nivel bancario y protocolos de seguridad para proteger tu información sensible.',
    'features.support.title': 'Reserva automática de citas',
    'features.support.description': 'Personas reales disponibles las 24 horas para ayudar cuando necesites asistencia.',
    'features.integration.title': 'Soporte de asesor humano',
    'features.integration.description': 'Funciona con sistemas y plataformas existentes que ya usas.',
    'features.multilingual.title': 'Almacenamiento seguro de documentos',
    'features.multilingual.description': 'Soporte completo para múltiples idiomas con comprensión a nivel nativo.',
    'features.accessibility.title': 'Integración de calendario',
    'features.accessibility.description': 'Diseñado para usuarios de todas las habilidades con características de accesibilidad integrales.',
    'features.realtime.title': 'Procesamiento de formularios en tiempo real',
    'features.realtime.description': 'Procesa formularios al instante con asistencia y validación de IA en tiempo real.',
    'features.availability.title': 'Disponibilidad 24/7',
    'features.availability.description': 'Nuestra plataforma está disponible las 24 horas para ayudarte cuando lo necesites.',
    'features.learnMore': 'Saber Más',
    
    // Why Mein Genie
    'why.title': '¿Por qué elegir Mein Genie?',
    'why.subtitle': 'Únete a miles que ya han simplificado sus vidas administrativas.',
    'why.timeSaved.title': 'Tiempo Ahorrado',
    'why.timeSaved.description': 'Promedio de 5 horas ahorradas por semana en tareas administrativas.',
    'why.accuracy.title': 'Tasa de Precisión',
    'why.accuracy.description': 'Completado de formularios impulsado por IA con verificación humana.',
    'why.satisfaction.title': 'Satisfacción del Usuario',
    'why.satisfaction.description': 'Calificado como excelente por usuarios de todas las demografías.',
    'why.languages.title': 'Idiomas Soportados',
    'why.languages.description': 'Soporte completo para los principales idiomas mundiales.',
    
    // Testimonials
    'testimonials.title': 'Lo que Dicen Nuestros Usuarios',
    'testimonials.subtitle': 'Historias reales de personas que han transformado su experiencia administrativa.',
    
    // Footer
    'footer.description': 'Transformando la burocracia a través de la automatización inteligente y la empatía humana.',
    'footer.product': 'Producto',
    'footer.company': 'Empresa',
    'footer.support': 'Soporte',
    'footer.legal': 'Legal',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cookies': 'Política de Cookies',
    'footer.rights': 'Todos los derechos reservados.',
    
    // Pages
    'formino.title': 'Formino - Asistente Inteligente de Formularios',
    'formino.subtitle': 'Transforma cualquier formulario en una conversación simple',
    'formino.description': 'Sube, escanea o enlaza cualquier formulario gubernamental, aplicación o documento. Nuestra IA te guiará para completarlo en tu idioma nativo.',
    'formino.howItWorks': 'Cómo Funciona',
    'formino.step1': 'Sube o escanea tu formulario',
    'formino.step2': 'Chatea con nuestra IA en tu idioma',
    'formino.step3': 'Revisa y envía tu formulario completado',
    'formino.getStarted': 'Comenzar',
    
    'termino.title': 'Termino - Reserva Inteligente de Citas',
    'termino.subtitle': 'Nunca más esperes en espera',
    'termino.description': 'Nuestro asistente de IA hace llamadas telefónicas por ti, reserva citas y gestiona tu calendario automáticamente.',
    'termino.howItWorks': 'Cómo Funciona',
    'termino.step1': 'Dinos qué cita necesitas',
    'termino.step2': 'Nuestra IA llama y reserva por ti',
    'termino.step3': 'Recibe confirmación y actualización del calendario',
    'termino.getStarted': 'Comenzar',
    
    'about.title': 'Acerca de Mein Genie',
    'about.subtitle': 'Simplificando la burocracia para todos',
    'about.description': 'Creemos que navegar los servicios gubernamentales y las tareas administrativas debería ser simple, accesible y libre de estrés para todos, independientemente de las barreras del idioma o la experiencia técnica.',
    'about.mission': 'Nuestra Misión',
    'about.missionText': 'Eliminar las barreras burocráticas y empoderar a las personas para acceder a servicios y completar tareas administrativas con confianza y facilidad.',
    'about.vision': 'Nuestra Visión',
    'about.visionText': 'Un mundo donde las barreras del idioma y los formularios complejos nunca impidan a nadie acceder a los servicios que necesitan.',
    
    'pricing.title': 'Elige tu Plan',
    'pricing.subtitle': 'Precios flexibles para individuos y familias',
    'pricing.basic': 'Básico',
    'pricing.pro': 'Pro',
    'pricing.enterprise': 'Empresarial',
    'pricing.monthly': 'por mes',
    'pricing.yearly': 'por año',
    'pricing.features': 'Características incluidas:',
    'pricing.getStarted': 'Comenzar',
    'pricing.contactUs': 'Contáctanos',
    
    'help.title': 'Centro de Ayuda',
    'help.subtitle': 'Encuentra respuestas a tus preguntas',
    'help.faq': 'Preguntas Frecuentes',
    'help.guides': 'Guías de Usuario',
    'help.contact': 'Contactar Soporte',
    'help.searchPlaceholder': 'Buscar ayuda...',
    
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Ponte en contacto con nuestro equipo',
    'contact.name': 'Nombre Completo',
    'contact.email': 'Dirección de Email',
    'contact.subject': 'Asunto',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.phone': 'Teléfono',
    'contact.address': 'Dirección',
    'contact.hours': 'Horario de Atención',
    
    // Common
    'common.download': 'Descargar archivo PDF',
    'common.upload': 'Subir archivo',
    'common.camera': 'Escanear con cámara',
    'common.microphone': 'Interacción por voz',
    'common.chat': 'Chat de texto',
    'common.review': 'Revisar formulario',
    'common.support': 'Obtener soporte',
    'common.loading': 'Cargando...',
    'common.error': 'Error ocurrido',
    'common.success': 'Éxito',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
